[build]
[build.environment]
  HUGO_VERSION = "0.61.0"
  RUBY_VERSION = "2.6.2"

[context.production]
  command = "hugo --gc"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL -e preview"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL -e branch"
