[build]
[build.environment]
  HUGO_VERSION = "0.52"

[context.production]
  command = "npx gulp && hugo --gc --minify"
[context.production.environment]
  HUGO_VERSION = "0.52"
  HUGO_ENV     = "production"

[context.deploy-preview]
  command = "npx gulp && hugo -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.52"

[context.branch-deploy]
  command = "npx gulp && hugo -b $DEPLOY_PRIME_URL"
[context.branch-deploy.environment]
  HUGO_VERSION = "0.52"
